# use Docker-based container (instead of OpenVZ)
sudo: false

env:
   - commons.user = FAKE_COMMONS_USER
   - commons.password = FAKE_COMMONS_USER
   - db.default.username = FAKE_WLXJURY_DB_USER
   - db.default.password = FAKE_WLXJURY_DB_PASSWORD

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala

scala:
   - 2.11.8

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script: "sbt clean coverage test"
after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)
